# Generated by Django 2.1.15 on 2020-05-17 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subjectname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to=settings.AUTH_USER_MODEL, verbose_name='教えられること'),
        ),
    ]
